import {ClerkProvider} from '@clerk/nextjs'
import '@/app/globals.css'
import type {Metadata} from "next";
import {ThemeProvider} from "next-themes";
import {Open_Sans} from "next/font/google";
import {cn} from "@/lib/utils";

const font = Open_Sans({subsets: ['latin']})
export const metadata: Metadata = {
    title: "Discord clone",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
            <body className={cn(
                font.className,
                "bg-white dark:bg-[#313338]"
            )}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem={false}
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    )
}